//@GeneratedCode
/*****************************************************************************************
  Please note that this file is regenerated each time it is generated
  and all your changes will be overwritten in this file.
  If you still want to make changes, you can do this in 2 ways:
  
  1. Use a 'partial class name' according to the following pattern:
  
  #if GENERATEDCODE_ON
  namespace_name {
    partial class ClassName
    {
      partial void BeforeExecute(ref bool handled)
      {
        //... do something
        handled = true;
      }
    }
   }
  #endif
  
  2. Change the label //@GeneratedCode to //@CustomizedCode, for example.
     Alternatively, you can also remove the label or give it a different name.
*****************************************************************************************/
namespace SEPayWithFun.Logic.DataContext
{
    /// <summary>
    /// Generated by the generator
    /// </summary>
    partial class ProjectDbContext
    {
        #region properties
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        private DbSet<Entities.Payment> DbPaymentSet { get; set; }
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public Contracts.IEntitySet<Entities.Payment> PaymentSet => GetEntitySet<Entities.Payment>();
        #endregion properties

        #region partial methods
        /// <summary>
        /// Generated by the generator
        /// </summary>
        partial void GetGeneratorDbSet<E>(ref DbSet<E>? dbSet, ref bool handled) where E : Entities.DbObject
        {
            if (typeof(E) == typeof(Entities.Payment))
            {
                dbSet = DbPaymentSet as DbSet<E>;
                handled = true;
            }
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        partial void GetGeneratorEntitySet<E>(ref EntitySet<E>? entitySet, ref bool handled) where E : Entities.EntityObject, new()
        {
            if (typeof(E) == typeof(Entities.Payment))
            {
                entitySet = new DataContext.PaymentSet(this, DbPaymentSet) as EntitySet<E>;
                handled = true;
            }
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        partial void GetGeneratorViewSet<E>(ref ViewSet<E>? viewSet, ref bool handled) where E : Entities.ViewObject, new()
        {
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static partial void OnViewModelCreating(ModelBuilder modelBuilder)
        {
        }
        #endregion partial methods
    }
}
